/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#5f5e5e",
        "on-secondary": "#ffffff",
        error: "#a64542",
        "on-primary": "#faf7f6",
        outline: "#838176",
        surface: "#fffbff",
        "primary-fixed-dim": "#d6d4d3",
        "on-surface-variant": "#66655a",
        "on-error": "#ffffff",
        "outline-variant": "#bcb9ad",
        tertiary: "#4d6877",
        "primary-dim": "#535252",
        "on-tertiary-fixed-variant": "#486272",
        "on-primary-fixed-variant": "#5c5b5b",
        "secondary-dim": "#555959",
        "secondary-fixed": "#e1e3e3",
        "error-dim": "#4e0309",
        "surface-variant": "#ece8db",
        "surface-container-high": "#f1eee2",
        "surface-dim": "#e6e3d4",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#c2def0",
        "on-secondary-fixed-variant": "#595c5d",
        "surface-container-low": "#D4D2D0",
        "primary-container": "#e5e2e1",
        "on-secondary-container": "#4f5253",
        "background": "#fffbff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#0f0e0b",
        "surface-container-highest": "#ece8db",
        "secondary-container": "#e1e3e3",
        "secondary-fixed-dim": "#d2d5d5",
        "on-surface": "#39382f",
        "error-container": "#fe8983",
        "on-background": "#39382f",
        "on-secondary-fixed": "#3c4040",
        "on-primary-fixed": "#403f3f",
        "on-primary-container": "#525151",
        "on-error-container": "#752121",
        "inverse-primary": "#ffffff",
        "inverse-on-surface": "#9f9d97",
        "tertiary-dim": "#415c6b",
        "primary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#2c4655",
        "surface-bright": "#fffbff",
        "tertiary-container": "#d0ecff",
        secondary: "#626565",
        primary: "#5f5e5e",
        "surface-container": "#f7f3ea",
        "on-tertiary-container": "#3e5868",
        "tertiary-fixed": "#d0ecff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
